### PR TITLE
Fix broken download link for Linux Ubuntu 14.04

### PR DESCRIPTION
**Pull request by pocketjoso**
Hey,

**DON'T MERGE THIS**

It needs to be properly fixed up; I would have raised an issue but can't on a fork. I dunno how to check between different version of Ubuntu on Linux, and it's also annoying that [bprodoehl prefixed his latest release with 'v'](https://github.com/bprodoehl/phantomjs/releases/); those two things need to be handled and then this fix can go in.

Needed as currently this package fails to install on Linux. (at least on Ubuntu 14.04).

Cheers

### CODE REVIEW

**Comment by pocketjoso** [comment]
This PR makes the `node install.js` command work on Ubuntu 14.04, but npm installing my fork still errored..

**Comment by tomoguisuru** [comment]
screen shot 2015-08-24 at 1 33 46 pm
@pocketjoso were you able to make any progress on this? We're having the same issue when using Ubuntu

**Comment by pocketjoso** [comment]
@tomoguisuru I haven't looked at it further, but I do really need a functioning Linux version of Phantom2 from npm as well..

**Comment by gramanathaiah** [comment]
hey when can we get this fixed since we are having a failure on amazon ec2 instance with the same error as above

**Comment by gumeniukcom** [comment]
same problem on ubuntu 14.04

```
$ npm install
\
> phantomjs2@2.0.0 install /home/sss/fff/node_modules/phantomjs2
> node install.js

PhantomJS detected, but wrong version 1.9.0 @ /usr/bin/phantomjs.
Downloading https://github.com/bprodoehl/phantomjs/releases/download/2.0.0-20141016/phantomjs-2.0.0-20141016-linux-x86_64.zip
Saving to /tmp/phantomjs/phantomjs-2.0.0-20141016-linux-x86_64.zip
Receiving...
Install exited unexpectedly
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/opt/nvm/versions/node/v0.12.7/bin/node" "/opt/nvm/versions/node/v0.12.7/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! phantomjs2@2.0.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs2@2.0.0 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sss/fff/npm-debug.log
```

```
$ tail /home/sss/fff/npm-debug.log
4443 silly gentlyRm containing path /home/sss/fff is under npm's control, in /home/sss/fff
4444 silly gentlyRm deletion target /home/sss/fff/node_modules/.bin/phantomjs is under /home/sss/fff
4445 verbose gentlyRm vacuuming from /home/sss/fff/node_modules/.bin/phantomjs up to /home/sss/fff
4446 silly vacuum-fs removing /home/sss/fff/node_modules/.bin/phantomjs
4447 silly vacuum-fs quitting because other entries in /home/sss/fff/node_modules/.bin
4448 info postuninstall phantomjs2@2.0.0
4449 silly gentlyRm /home/sss/fff/node_modules/phantomjs2 is being purged from base /home/sss/fff
4450 verbose gentlyRm don't care about contents; nuking /home/sss/fff/node_modules/phantomjs2
4451 silly vacuum-fs purging /home/sss/fff/node_modules/phantomjs2
4452 silly vacuum-fs quitting because other entries in /home/sss/fff/node_modules
```

**Comment by jangot** [comment]
+1

**Comment by mperice** [comment]
+1

**Comment by ewnd9** [comment]
+1

**Comment by betasve** [comment]
still doesn't work for me on Ubuntu 14.04: 

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'request-progress'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/sly/Downloads/phantomjs2/install.js:9:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

Pulled the current branch and tried `node install.js` but it threw the upper mentioned errors.

Thanks in advance.

**Comment by khaledosman** [comment]
Doesn't work on Ubuntu 15 either, npm version 3.2.2, node version 0.12.7
phantomjs2

**Comment by docteurem** [comment]
+1

**Comment by tildedave** [comment]
So I dug into this a little bit because I thought it would be a pretty easy fix.  Unfortunately there are some issues with the current state of phantomjs2 pre-built binaries and this repo:
- Prebuilt binaries for 20150528 only exist for Ubuntu 14.04 or 15.04.  No MacOS X.  https://github.com/zeevl/phantomjs2/commit/6ce1325ef112a0eaf0f07357334daa248def447c https://github.com/bprodoehl/phantomjs/releases (basically master for this repo is broken for Mac OS X)
- Prebuilt MacOS X binary at https://bitbucket.org/ariya/phantomjs/downloads doesn't work on Yosemite
- Other people have built binaries for more recent versions of MacOS X but this has a different directory structure so I didn't dig in https://github.com/eugene1g/phantomjs/releases

What I've done for my project is patch this repo to use 20150528 for Linux and 2014016 for MacOS X.  You can see my patch here https://github.com/zeevl/phantomjs2/compare/master...tildedave:fix-ubuntu-14-04-installation - maybe this will be useful for someone.

**Comment by XianHain** [comment]
+1

**Comment by mihai-chiorean** [comment]
+1

**Comment by vampolo** [comment]
Hi,

Still having issues

```
npm install phantomjs2 
npm WARN install Couldn't install optional dependency: Unsupported

> phantomjs2@2.0.0 install /home/vampolo/node_modules/phantomjs2
> node install.js

Downloading https://github.com/bprodoehl/phantomjs/releases/download/2.0.0-20141016/phantomjs-2.0.0-20141016-linux-x86_64.zip
Saving to /tmp/phantomjs/phantomjs-2.0.0-20141016-linux-x86_64.zip
Receiving...
Install exited unexpectedly
npm ERR! Linux 3.19.0-30-generic
npm ERR! argv "/home/vampolo/.nvm/versions/node/v4.1.1/bin/node" "/home/vampolo/.nvm/versions/node/v4.1.1/bin/npm" "install" "phantomjs2"
npm ERR! node v4.1.1
npm ERR! npm  v3.3.4
npm ERR! code ELIFECYCLE

npm ERR! phantomjs2@2.0.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs2@2.0.0 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vampolo/Sysdig/frontend/npm-debug.log
```

**Comment by kevin-abl** [comment]
+1

**Comment by zack9433** [comment]
+1

**Comment by javiercr** [comment]
+1 :(

**Comment by kevin-abl** [comment]
For all who are still stuck on this, I was able to get PhantomJS built on my servers using the Linux instructions here:

http://phantomjs.org/build.html

It takes forever, but it works.

Would still be great to get an npm package though.

**Comment by pocketjoso** [comment]
You don't need to build from scratch. You can follow these steps (if you don't care about the npm package) -- only tested on `Linux Ubuntu 14.04`
- `apt-get update`
- `apt-get install -y g++ flex bison gperf ruby perl libsqlite3-dev libfontconfig1-dev libicu-dev libfreetype6 libssl-dev libpng-dev libjpeg-dev make git libqt5webkit5-dev libwebp5` (probably a few packaged here that aren't actually needed)
- `git clone https://github.com/pocketjoso/phantomjs2`
- cd into dir
- `npm install`
- `node ./install.js`
- move generated binary onto your path, f.e. `/usr/bin/phantomjs`

**Comment by ldeavila** [comment]
Module wont install on CentOS 7 either

**Comment by zeevl** [comment]
Ok, after long last. 

There's still no officially blessed, statically linked version of phantomjs 2.0 that will work on the various linux distros.  See https://github.com/ariya/phantomjs/issues/12948.

So instead of trying to fix each of these individually, there's now support for pointing `PHANTOMJS_DOWNLOADURL`  to whatever zipped/tarred binary url will work for your env, either on the command line or in .npmrc.     See the README. 

The aforementioned phantomjs issue has a number of the necessary links to various linux distros -- refer to that for your overrides.   Hopefully this will work for everyone. 

Support for windows and the workaround for yosemite are included in 2.0.1 by default.

**Comment by pocketjoso** [comment]
Cheers @zeevl - great!
